### ISSUE TITLE
Leaflet Map does not Center to Location after search

### ISSUE THREAD

**Issue by NightFury555** [smeijer/leaflet-geosearch#229] opened 2020-07-03 04:18 UTC
Hi,

For some reason, the map does not center to the point of search result. 
It is able to autoComplete, but nothing happens after that.

I tried to check the object output from the search.
`                  
                  mymap.on('geosearch/showlocation', function(result) {
                    console.log(result);
                   });
`

However, it returned a "TypeError: Cannot convert undefined or null to object".

Hope that someone can assist. Thank you!!

**Comment by rawhasan** [comment] 2020-07-21 18:22
Me too getting the same error. Please let know if you've found a solution for this.

**Comment by qzminski** [comment] 2020-08-04 11:51
Same problem, the source of an error seems to be located in https://github.com/smeijer/leaflet-geosearch/blob/develop/src/SearchControl.ts#L360

**Comment by qzminski** [comment] 2020-08-04 12:03
Looks like once I updated from 3.0.0 to 3.0.5 the problem is gone.

**Comment by smeijer** [comment] 2020-08-04 18:41
@NightFury555 & @rawhasan, which version do you use?

**Comment by yuriizinets** [comment] 2020-09-22 17:58
Seems like problem already fixed in the latest patch releases.
I'll close this issue, but if you're still getting this behaviour, please, re-open it.

**Closed by yuriizinets** 2020-09-22 17:58 UTC

**Comment by nobbiexxx** [comment] 2022-04-07 13:34
I'm getting the same thing with version 3.6.0
Has anyone figured it out?

**Comment by Cheppar** [comment] 2022-12-16 08:05
Hello [nobbiexxx](https://github.com/nobbiexxx) 
All i did was to update the version in the link and script.
` <link
        rel="stylesheet"
        href="https://unpkg.com/leaflet-geosearch@3.6.0/dist/geosearch.css"
      />`
      
      <script src="https://unpkg.com/leaflet-geosearch@3.6.0/dist/geosearch.umd.js"></script>
      
      This worked for me, I hope it does for you.
