### ISSUE TITLE
error cors

### ISSUE THREAD

**Issue by uxitten** [smeijer/leaflet-geosearch#171] opened 2018-07-16 13:38 UTC
i have get error cors when use leaflet-geosearch

<img width="778" alt="screen shot 2018-07-16 at 6 06 28 pm" src="https://user-images.githubusercontent.com/1549069/42761583-3391febe-8923-11e8-8bd6-0997c0118a04.png">

**Comment by ignacy130** [comment] 2018-07-16 18:14
Try explicit request like:
`var results = await this.$http.get('https://nominatim.openstreetmap.org/search?format=json&q=' + encodeURIComponent(this.query + ", Warsaw, Poland"));`

**Comment by uxitten** [comment] 2018-07-16 18:33
this?

Where

**Comment by uxitten** [comment] 2018-07-17 04:11
@ignacy130  What's the difference?

**Comment by rousos87** [comment] 2018-07-21 11:54
@ignacy130 The problem is because you are using http instead of https. Unfortunately there is a pull request here (https://github.com/smeijer/leaflet-geosearch/pull/164) but is not merged yet. Nominatim project announced that from now one you have to use https. One easy way to do it,is to change the file inside dist folder. 

Replace this: 

> return `${protocol}//nominatim.openstreetmap.org/search?${paramString}`;

with this

return `https://nominatim.openstreetmap.org/search?${paramString}`;

Hope it helps

**Comment by smeijer** [comment] 2018-07-23 09:47
Closed by 04cab81. Thanks for the support @ignacy130 and @rousos87. Sorry it took so long.

**Closed by smeijer** 2018-07-23 09:47 UTC
