### ISSUE TITLE
leafletControl autoSearch function wrong event.target, undefined query

### ISSUE THREAD

**Issue by AlexandrePhilibert** [smeijer/leaflet-geosearch#214] opened 2020-03-27 23:46 UTC
There seems to be an issue with the way event are handled in the leafletControl.

What I am doing : 
```javascript
constructor() {
        super();

        this._provider = new OpenStreetMapProvider();
        this._searchControl = new GeoSearchControl({
            provider: this._provider
        })

        // creating leaflet map here

        this._map.addControl(this._searchControl);
    }
```

As i am typing in the GeoSearchControl, keyup events are fired but the `event.target` used in the `autoSearch` function is not the input, resulting in undefined query.

I am using Lit-Element, Webpack and Leaflet v1.6.0

could the `event.target` be changed to `event.originalTarget` ?

**Comment by AlexandrePhilibert** [comment] 2020-03-28 00:07
Well this fix is not working on chrome

**Comment by smeijer** [comment] 2020-04-27 13:52
Do you have a repo somewhere so that I can test it?

**Comment by smeijer** [comment] 2020-05-23 12:37
Closing, as I'm unable to reproduce. Please let me know if it still exists.

**Closed** 2020-05-23 12:37 UTC
Labels: bug
