### ISSUE TITLE
Event Listeners after showlocation

### ISSUE THREAD

**Issue by Greg-Gravyty** [smeijer/leaflet-geosearch#140] opened 2017-07-31 22:07 UTC
I recently upgraded from 2.4.0 to 2.5.0, so that I could get the fix that allows you to highlight text in the search box (#138). 
However, once I upgraded, it appears that the handlers don't get restored after I search and select that search. I got a workaround by manually enabling them:
`map.on('geosearch/showlocation', function(e) {
    map['dragging'].enable();
    ...
});
`
I thought that you'd like to try to reproduce this bug. Maybe it's because the `mouseout` event doesn't get fired when you select a dropdown. I haven't debugged leaflet-geosearch enough yet to say for sure.

**Comment by smeijer** [comment] 2017-07-31 22:23
Thanks for reporting. This sounds like a serious bug. I'll take a look at it tomorrow.

**Comment by smeijer** [comment] 2017-08-01 09:22
I can't seem to reproduce this bug. How are you selecting the search result? Can you give me a step-by-step instruction?

**Comment by Greg-Gravyty** [comment] 2017-08-02 23:32
![geosearch_bug](https://user-images.githubusercontent.com/27287151/28899445-150610b0-77b9-11e7-9b7f-b2b8cd3cd079.gif)

Here's a gif of the bug in action. It's reproducible 100% of the time with my code. Again that's leaflet@1.1.0 and leaflet-geosearch@2.5.0. The code for this page is kind of complicated, because I use a custom Provider that combines my airport dataset with OpenStreetMap. It's probably something that I did that broke this. Here are the relevant parts:
```javascript
        var GeoSearchControl = window.GeoSearch.GeoSearchControl;
        var Provider = window.GeoSearch.Provider;
        class CustomProvider extends Provider {
            constructor() {
                super();
                this.data;
                airports_ajax();
            }
            async search({ query }) {
                const airports = this.parse_airports({data:this.data});
                const airports_filtered = airports.filter(x => x.label.toLowerCase().includes(query.toLowerCase()));
                if (airports.filter(x => x.label === query).length == 1) {
                    return airports_filtered;
                }
                const url = this.endpoint({ query });
                const request = await fetch(url);
                const streets = await request.json();
                const parsed_streets = this.parse_open({ data: streets });
                const coded = airports.filter(x => x.code.toLowerCase().includes(query.toLowerCase()));
                if (coded.length == 1) {
                    return coded;
                }
                if (parsed_streets.length == 1) {
                    return parsed_streets;
                }
                return coded.concat(airports_filtered).concat(parsed_streets);
            }
            endpoint({ query } = {}) {
                const paramString = this.getParamString({
                    format: 'json',
                    q: query,
                });
                return `https://nominatim.openstreetmap.org/search?${paramString}`;
            }
            parse_open({ data }) {
                return data.map(r => ({
                    x: r.lon,
                    y: r.lat,
                    label: r.display_name,
                    bounds: [
                        [parseFloat(r.boundingbox[0]), parseFloat(r.boundingbox[2])], // s, w
                        [parseFloat(r.boundingbox[1]), parseFloat(r.boundingbox[3])], // n, e
                    ],
                    raw: r,
                }));
            }
            parse_airports({data}) {
                if (typeof(data) != 'undefined') {
                    return data.map(r => ({
                        x: r.fields.longitude,
                        y: r.fields.latitude,
                        label: r.fields.label + ' (' + r.fields.code + ')',
                        code: r.fields.code,
                        id: r.pk,
                    }));
                }
                else {
                    return [];
                }
            }
        }

        var search = new CustomProvider();

        const airportControl = new GeoSearchControl({
            provider: search,
            searchLabel: 'Enter location or airport...',
            position: 'topleft',
            style: 'bar',
            classNames: {
                container: 'leaflet-bar leaflet-control leaflet-control-geosearch',
                resetButton: 'reset',
                msgbox: 'leaflet-bar message',
                form: '',
                input: '',
            },
            autoComplete: true,
            autoCompleteDelay: 250,
            maxMarkers: 0,
            animateZoom: false,
            autoClose: true,
        }).addTo(map);
```

**Comment by smeijer** [comment] 2017-08-03 09:25
Seems to be in the `autoClose`.

**Comment by smeijer** [comment] 2017-08-03 10:36
Fixed in `v2.5.1`. Can you let me know if it works for you?

**Closed** 2017-08-03 10:35 UTC
Labels: bug

**Comment by Greg-Gravyty** [comment] 2017-08-03 14:11
I use unpkg. Can you publish `v2.5.1` to npm?

**Comment by smeijer** [comment] 2017-08-03 14:23
Sorry, I incorrectly assumed I already did that. Now it's done for sure 😄 

https://unpkg.com/leaflet-geosearch@latest
https://unpkg.com/leaflet-geosearch@2.5.1/

**Comment by Greg-Gravyty** [comment] 2017-08-03 14:36
Fixed! Thanks for the great plugin and quick bugfix! :+1:

**Comment by smeijer** [comment] 2017-08-03 14:42
You're welcome. Thanks for the report and testing.
