### ISSUE TITLE
Google.maps Error while building / compiling

### ISSUE THREAD

**Issue by jimit-raval-roambee** [smeijer/leaflet-geosearch#350] opened 2022-10-06 17:05 UTC
Hello,
**We have faced this error while building angular build ( angular v9 )**

error TS2688: Cannot find type definition file for 'google.maps'.

16 /// <reference types="google.maps" />
----------------------------------------------------------------------------
error TS2688: Cannot find type definition file for 'google.maps'.

1 /// <reference types="google.maps" />

<img width="814" alt="err" src="https://user-images.githubusercontent.com/104071963/194375240-0089b2de-1c32-4da6-8453-ce65e488702a.PNG">

Thanks

**Comment by kstratis** [comment] 2022-10-10 05:55
Hi, please see this comment: https://github.com/smeijer/leaflet-geosearch/issues/349#issuecomment-1272816171

**Comment by smeijer** [comment] 2022-10-10 18:06
Closing as duplicate of #349, solution/workaround here: https://github.com/smeijer/leaflet-geosearch/issues/349#issuecomment-1273622757

**Closed by smeijer** 2022-10-10 18:06 UTC
